import { Box, Center, Heading, SimpleGrid } from '@chakra-ui/react'
import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

const Project = ({data}) => {
  return (
    <Box>
           <Head>
        <title>portfolio App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Heading>Projects</Heading>
          <Center gap={10}>
        <SimpleGrid columns={2}>
        {
            data.map((dat)=>(
              <Link href={dat.html_url} key={dat.id}>
                    <Box border={'solid 1px black'}>
                        <Heading size={'md'}>{dat.full_name}</Heading>
                        <Heading size={'md'}>{dat.language}</Heading>
                        <h1>fork : {dat.forks_count}</h1>
                  
                        <h1>star : {dat.stargazers_count}</h1>
                        </Box> 
                </Link>
            ))
          }
        </SimpleGrid>
          </Center>
    </Box>
  )
}

export const getServerSideProps=async()=>{
    const res=await fetch("https://api.github.com/search/repositories?q=user:mhdsadique+fork:true&sort=updated&per_page=10&type=Repositories")
    const datas=await res.json()
    return{
      props:{
        data:datas.items
      }
    }
  }

